DROP TABLE IF EXISTS Currencies;


CREATE table Currencies (
    id int generated by default as identity primary key ,
    charcode varchar,
    dateofcreation date,
    name varchar,
    nominal varchar,
    numcode varchar,
    value varchar
);

INSERT INTO  Currencies (charcode, dateofcreation, name, nominal, numcode, value)
VALUES ('USD', '2023-04-29', 'Dollar', '1', '840', '80,5093');