DROP TABLE IF EXISTS
    goal;



CREATE TABLE IF NOT EXISTS goal (
                                   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   text VARCHAR(50) NOT NULL,
                                   price INTEGER NOT NULL,
                                   userId INTEGER NOT NULL
);
