server:
  port: 8083

cbr:
  url: https://cbr.ru/scripts/XML_daily.asp

spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/parser
   username: admin
   password: admin
   driver-class-name: org.postgresql.Driver